# Generated by Django 4.0.3 on 2022-06-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
