# Generated by Django 4.0.3 on 2022-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
